apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n9e-alter-service-data
  namespace: n9e-alter-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
