apiVersion: v1
kind: Secret
metadata:
  name: n9e-alter-service-tls
  namespace: n9e-alter-service
type: kubernetes.io/tls
data:
  # Base64-encoded certificate (PEM)
  tls.crt: ""
  # Base64-encoded private key (PEM)
  tls.key: ""
